#############################################################################
##  v      #                   The Coq Proof Assistant                     ##
## <O___,, #                INRIA - CNRS - LIX - LRI - PPS                 ##
##   \VV/  #                                                               ##
##    //   #  Makefile automagically generated by coq_makefile Vtrunk      ##
#############################################################################

# WARNING
#
# This Makefile has been automagically generated
# Edit at your own risks !
#
# END OF WARNING

#
# This Makefile was generated by the command line :
# coq_makefile -f Make -o Makefile 
#

.DEFAULT_GOAL := all

# 
# This Makefile may take arguments passed as environment variables:
# COQBIN to specify the directory where Coq binaries resides;
# ZDEBUG/COQDEBUG to specify debug flags for ocamlc&ocamlopt/coqc;
# DSTROOT to specify a prefix to install path.

# Here is a hack to make $(eval $(shell works:
define donewline


endef
includecmdwithout@ = $(eval $(subst @,$(donewline),$(shell { $(1) | tr '\n' '@'; })))
$(call includecmdwithout@,$(COQBIN)coqtop -config)

##########################
#                        #
# Libraries definitions. #
#                        #
##########################

COQLIBS?= -R . EuclideanGeometry
COQDOCLIBS?=-R . EuclideanGeometry

##########################
#                        #
# Variables definitions. #
#                        #
##########################


OPT?=
COQFLAGS?=-q $(OPT) $(COQLIBS) $(OTHERFLAGS) $(COQ_XML)
COQCHKFLAGS?=-silent -o
COQC?=$(COQBIN)coqc
COQDEP?=$(COQBIN)coqdep -c
GALLINA?=$(COQBIN)gallina
COQDOC?=$(COQBIN)coqdoc
COQCHK?=$(COQBIN)coqchk

##################
#                #
# Install Paths. #
#                #
##################

ifdef USERINSTALL
XDG_DATA_HOME?=$(HOME)/.local/share
COQLIBINSTALL=$(XDG_DATA_HOME)/coq
COQDOCINSTALL=$(XDG_DATA_HOME)/doc/coq
else
COQLIBINSTALL=${COQLIB}user-contrib
COQDOCINSTALL=${DOCDIR}user-contrib
endif

######################
#                    #
# Files dispatching. #
#                    #
######################

VFILES:=geom.v\
  N7_Tactics.v\
  N6_ParallelAndPerpendicularLines.v\
  N5_UniqueParallel.v\
  N4_DiscreteThales.v\
  N3_ParallelOpposedLine.v\
  N2_DrawingParallelLine.v\
  N1_DrawingPerpendicularLines.v\
  M5_Tactics.v\
  M4_PerpendicularLines.v\
  M3_SecantLines.v\
  M2_ParallelLines.v\
  M1_SuperImposedLines.v\
  L6_Tactics.v\
  L5_nParallelogramm.v\
  L4_ParallelogrammAngles.v\
  L3_EquidirectedParallelogramm.v\
  L2_StrictParallelogramm.v\
  L1_Parallelogramm.v\
  K3_Tactics.v\
  K2_MidLineandRightAngle.v\
  K1_RightAngle.v\
  J4_Tactics.v\
  J3_MidProp.v\
  J2_MidPoint.v\
  J1_MidLine.v\
  I4_Tactics.v\
  I3_OpposedAngles.v\
  I2_Supplement.v\
  I1_SupplementaryAngle.v\
  H4_Tactics.v\
  H3_BuildingTriangle.v\
  H2_ParticularTriangles.v\
  H1_Triangles.v\
  G4_Tactics.v\
  G3_ParticularAngle.v\
  G2_AngleProp.v\
  G1_Angles.v\
  F5_Tactics.v\
  F4_ArchimedianDistance.v\
  F3_Graduation.v\
  F2_MarkSegment.v\
  F1_IntersectionDiameterProp.v\
  E4_Tactics.v\
  E3_FourPointsIntersection.v\
  E2_NotEquidirectedIntersection.v\
  E1_IntersectionLinesProp.v\
  D5_Tactics.v\
  D4_DistanceLt.v\
  D3_SecondDimension.v\
  D2_ExistsClockwise.v\
  D1_IntersectionCirclesProp.v\
  C7_Tactics.v\
  C6_DistanceTimesN.v\
  C5_TriangularInequality.v\
  C4_DistanceLe.v\
  C3_SumDistance.v\
  C2_CircleAndDistance.v\
  C1_Distance.v\
  B7_Tactics.v\
  B6_EquiDirectedProp.v\
  B5_BetweenProp.v\
  B4_RaysProp.v\
  B3_EquiOrientedProp.v\
  B2_CollinearProp.v\
  B1_ClockwiseProp.v\
  A7_Tactics.v\
  A6_Intersection.v\
  A5_Cercle.v\
  A4_Droite.v\
  A3_Metrique.v\
  A2_Orientation.v\
  A1_Plan.v

-include $(addsuffix .d,$(VFILES))
.SECONDARY: $(addsuffix .d,$(VFILES))

VOFILES:=$(VFILES:.v=.vo)
GLOBFILES:=$(VFILES:.v=.glob)
VIFILES:=$(VFILES:.v=.vi)
GFILES:=$(VFILES:.v=.g)
HTMLFILES:=$(VFILES:.v=.html)
GHTMLFILES:=$(VFILES:.v=.g.html)

#######################################
#                                     #
# Definition of the toplevel targets. #
#                                     #
#######################################

all: $(VOFILES) 

spec: $(VIFILES)

gallina: $(GFILES)

html: $(GLOBFILES) $(VFILES)
	- mkdir -p html
	$(COQDOC) -toc -html $(COQDOCLIBS) -d html $(VFILES)

gallinahtml: $(GLOBFILES) $(VFILES)
	- mkdir -p html
	$(COQDOC) -toc -html -g $(COQDOCLIBS) -d html $(VFILES)

all.ps: $(VFILES)
	$(COQDOC) -toc -ps $(COQDOCLIBS) -o $@ `$(COQDEP) -sort -suffix .v $^`

all-gal.ps: $(VFILES)
	$(COQDOC) -toc -ps -g $(COQDOCLIBS) -o $@ `$(COQDEP) -sort -suffix .v $^`

all.pdf: $(VFILES)
	$(COQDOC) -toc -pdf $(COQDOCLIBS) -o $@ `$(COQDEP) -sort -suffix .v $^`

all-gal.pdf: $(VFILES)
	$(COQDOC) -toc -pdf -g $(COQDOCLIBS) -o $@ `$(COQDEP) -sort -suffix .v $^`

validate: $(VOFILES)
	$(COQCHK) $(COQCHKFLAGS) $(COQLIBS) $(notdir $(^:.vo=))

beautify: $(VFILES:=.beautified)
	for file in $^; do mv $${file%.beautified} $${file%beautified}old && mv $${file} $${file%.beautified}; done
	@echo 'Do not do "make clean" until you are sure that everything went well!'
	@echo 'If there were a problem, execute "for file in $$(find . -name \*.v.old -print); do mv $${file} $${file%.old}; done" in your shell/'

.PHONY: all opt byte archclean clean install userinstall depend html validate

####################
#                  #
# Special targets. #
#                  #
####################

byte:
	$(MAKE) all "OPT:=-byte"

opt:
	$(MAKE) all "OPT:=-opt"

userinstall:
	+$(MAKE) USERINSTALL=true install

install:
	for i in $(VOFILES); do \
	 install -d `dirname $(DSTROOT)$(COQLIBINSTALL)/EuclideanGeometry/$$i`; \
	 install -m 0644 $$i $(DSTROOT)$(COQLIBINSTALL)/EuclideanGeometry/$$i; \
	done

install-doc:
	install -d $(DSTROOT)$(COQDOCINSTALL)/EuclideanGeometry/html
	for i in html/*; do \
	 install -m 0644 $$i $(DSTROOT)$(COQDOCINSTALL)/EuclideanGeometry/$$i;\
	done

clean:
	rm -f $(VOFILES) $(VIFILES) $(GFILES) $(VFILES:.v=.v.d) $(VFILES:=.beautified) $(VFILES:=.old)
	rm -f all.ps all-gal.ps all.pdf all-gal.pdf all.glob $(VFILES:.v=.glob) $(VFILES:.v=.tex) $(VFILES:.v=.g.tex) all-mli.tex
	- rm -rf html mlihtml

archclean:
	rm -f *.cmx *.o

printenv:
	@$(COQBIN)coqtop -config
	@echo CAMLC =	$(CAMLC)
	@echo CAMLOPTC =	$(CAMLOPTC)
	@echo PP =	$(PP)
	@echo COQFLAGS =	$(COQFLAGS)
	@echo COQLIBINSTALL =	$(COQLIBINSTALL)
	@echo COQDOCINSTALL =	$(COQDOCINSTALL)

Makefile: Make
	mv -f $@ $@.bak
	$(COQBIN)coq_makefile -f $< -o $@


###################
#                 #
# Implicit rules. #
#                 #
###################

%.vo %.glob: %.v
	$(COQC) $(COQDEBUG) $(COQFLAGS) $*

%.vi: %.v
	$(COQC) -i $(COQDEBUG) $(COQFLAGS) $*

%.g: %.v
	$(GALLINA) $<

%.tex: %.v
	$(COQDOC) -latex $< -o $@

%.html: %.v %.glob
	$(COQDOC) -html $< -o $@

%.g.tex: %.v
	$(COQDOC) -latex -g $< -o $@

%.g.html: %.v %.glob
	$(COQDOC) -html -g $< -o $@

%.v.d: %.v
	$(COQDEP) -slash $(COQLIBS) "$<" > "$@" || ( RV=$$?; rm -f "$@"; exit $${RV} )

%.v.beautified:
	$(COQC) $(COQDEBUG) $(COQFLAGS) -beautify $*

# WARNING
#
# This Makefile has been automagically generated
# Edit at your own risks !
#
# END OF WARNING

